language: python
python:
  - "3.6"
services:
  - postgresql
before_install:
  - sudo apt-get update
  - sudo apt-get install -y poppler-utils
install:
  - pip install -e .
  - pip install -e .[test]
  - pip install -U "git+https://github.com/sweh/python-fints.git#egg=fints"
script:
  - pytest
