env:
  global:
    - CC_TEST_REPORTER_ID=0069fc0d69294e56de0b134cd62f6be6d1ac6e8ed80a7e71a2770c1d166d93ff
language: python
python:
  - "3.6"
services:
  - postgresql
before_install:
  - sudo apt-get update
  - sudo apt-get install -y poppler-utils
install:
  - pip install -e .
  - pip install -e .[test]
  - pip install -U "git+https://github.com/sweh/python-fints.git#egg=fints"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - pytest
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
