name: allure-python-pytest

on:
  push:
    branches-ignore:
      - '!master'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 9 * * *'

jobs:
  autotests:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: allotmentclubtest
          POSTGRES_PASSWORD: asdf
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install needed software
        run: |
          sudo apt-get update
          sudo apt-get -yqq install poppler-utils

      - name: Run Test
        if: always()
        run: ./pytest
