name: python-pytest

on:
  push:
    branches-ignore:
      - '!master'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 9 * * *'

jobs:
  test:
    uses: risclog-solution/gha_workflow_templates/.github/workflows/pytest_appenv.yml@master
    with:
      timeout_minutes: 25
      versions: >-
        ["3.10",]

  coverage:
    needs: test
    uses: risclog-solution/gha_workflow_templates/.github/workflows/coverage.yml@master
    with:
      min_coverage: 80

  pre-commit:
    uses: risclog-solution/gha_workflow_templates/.github/workflows/pre_commit.yml@master

  publish-test-results:
    needs: test
    uses: risclog-solution/gha_workflow_templates/.github/workflows/publish_test_results.yml@master
